Include also hibernate core
Because got error of old jboss-logging version:
2016-08-29T10:37:10.444+03 ERROR {} [localhost-startStop-1] ERROR
org.springframework.web.context.ContextLoader: Context initialization
failed
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'emf' defined in class path resource
[META-INF/spring/context/dao-context.xml]: Invocation of init method
failed; nested exception is java.lang.NoSuchMethodError:
org.jboss.logging.Logger.debugf(Ljava/lang/String;I)V