Exclude old version of org.jboss.logging
Because still getting error on servers:
2016-08-30T16:35:53.425+03 ERROR {} [localhost-startStop-1] ERROR
org.springframework.web.context.ContextLoader: Context initialization
failed
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'emf' defined in class path resource
[META-INF/spring/context/dao-context.xml]: Invocation of init method
failed; nested exception is java.lang.NoSuchMethodError:
org.jboss.logging.Logger.debugf(Ljava/lang/String;I)V